const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1100}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  fs.mkdirSync('.preview', {recursive: true});
  try {
    await page.goto('http://localhost:8080/catalogue.html');
    await page.locator('.product-card').nth(11).waitFor();
    assert.equal(await page.locator('.product-card').count(), 12);
    assert.equal(await page.locator('.product-image-button .sample-badge').count(), 12);
    await page.screenshot({path: '.preview/catalogue-desktop.png', fullPage: true});
    await page.getByRole('button', {name: 'CCTV Systems', exact: true}).click();
    assert.equal(await page.locator('.product-card').count(), 2);
    await page.getByRole('button', {name: 'View 4MP Indoor Turret Camera', exact: true}).click();
    assert.equal(await page.locator('#detail-name').textContent(), '4MP Indoor Turret Camera');
    assert.ok((await page.locator('#detail-enquire').getAttribute('href')).includes('Product%20enquiry'));
    await page.screenshot({path: '.preview/product-detail.png'});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#product-dialog').evaluate(node => node.open), false);
    await page.locator('#search').fill('not-a-real-product');
    assert.equal(await page.locator('.product-card').count(), 0);
    await page.getByRole('button', {name: 'Clear filters'}).click();
    assert.equal(await page.locator('.product-card').count(), 12);
    await page.locator('#sort').selectOption('price-low');
    assert.match(await page.locator('.product-card').first().innerText(), /8-Port Gigabit/);
    await page.goto('http://localhost:8080/catalogue.html?category=WiFi%20Solutions');
    await page.locator('.product-card').nth(1).waitFor();
    assert.equal(await page.locator('.product-card').count(), 2);
    assert.equal(await page.locator('#category-title').textContent(), 'WiFi Solutions');
    await page.setViewportSize({width: 390, height: 844});
    await page.goto('http://localhost:8080/catalogue.html');
    await page.locator('.product-card').nth(11).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({path: '.preview/catalogue-mobile.png', fullPage: true});
    assert.equal(await page.locator('.product-image-button img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0)), true);
    await page.goto('http://localhost:8080/index.html');
    assert.equal(await page.locator('.service-link[href*="catalogue.html"]').count(), 10);
    await page.locator('.service-link').first().click();
    await page.locator('.product-card').nth(1).waitFor();
    assert.equal(await page.locator('#category-title').textContent(), 'CCTV Systems');
    await page.setViewportSize({width: 1440, height: 1100});
    await page.goto('http://localhost:8080/admin/');
    await page.getByRole('button', {name: 'Login setup pending'}).waitFor();
    assert.equal(await page.locator('#open-live').isDisabled(), true);
    await page.screenshot({path: '.preview/admin-workspace.png', fullPage: true});
    await page.getByRole('link', {name: 'Open editor demo'}).click();
    await page.waitForFunction(() => !!window.CMS, {timeout: 60000});
    await page.getByRole('button', {name: 'Login', exact: true}).click();
    await page.getByText('Products', {exact: true}).first().waitFor();
    assert.equal(await page.locator('#editor-error').isVisible(), false);
    await page.getByText('Products', {exact: true}).first().click();
    await page.waitForTimeout(1500);
    await page.frameLocator('iframe').locator('.product-card').nth(11).waitFor();
    await page.screenshot({path: '.preview/admin-editor.png', fullPage: true});
    console.log('Browser errors:', errors);
    assert.deepEqual(errors, []);
    console.log('Customer catalogue, image loading, mobile overflow, category links and admin setup checks passed.');
  } finally {await browser.close();}
})().catch(error => {console.error(error); process.exitCode = 1;});
