const {chromium} = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  let repriced = false, unpublished = false;
  let savedItems = [], savedVersion = 0;
  await page.addInitScript(() => sessionStorage.setItem('abtech-customer-session:/', JSON.stringify({token: 'a'.repeat(64), username: 'cart_test'})));
  await page.route('https://ab-tech-catalogue-auth.johern20154.workers.dev/customer/**', async route => {
    const request = route.request();
    if (request.method() === 'OPTIONS') return route.fulfill({status: 204, headers: {'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type,Authorization', 'Access-Control-Allow-Methods': 'GET,POST,PUT,OPTIONS'}});
    if (request.method() === 'PUT') {savedItems = request.postDataJSON().items; savedVersion++;}
    return route.fulfill({json: {username: 'cart_test', items: savedItems, version: savedVersion}, headers: {'Access-Control-Allow-Origin': '*'}});
  });
  const product = (id, name, price, price_mode) => ({id, name, price, price_mode, published: true, image: 'assets/products/cctv.svg', description: 'Cart test product', specifications: [], gallery: [], installation: 'Installation quoted separately.', availability: 'Confirm availability'});
  await page.route('**/data/categories/*.json', route => {
    const slug = new URL(route.request().url()).pathname.split('/').pop();
    const products = slug === 'cctv.json' ? [product('same-id', 'Fixed camera', repriced ? 12.35 : 10.25, 'fixed'), product('starting', 'Starting package', 20, 'from')].filter(p => !unpublished || p.id !== 'same-id') : slug === 'wifi.json' ? [product('same-id', 'Quote WiFi', 999, 'quote')] : [];
    return route.fulfill({json: {products}});
  });
  const open = () => page.locator('[data-cart-open]').click();
  const total = async () => {await page.waitForFunction(() => !document.querySelector('.cart-clear').disabled); return page.locator('#cart-total').textContent();};
  try {
    await page.goto('http://localhost:8080/catalogue.html?view=all');
    await page.locator('.product-card').nth(2).waitFor();
    await open(); await page.getByText('Your cart is empty', {exact: true}).waitFor();
    await page.getByRole('button', {name: 'Close cart', exact: true}).click();
    await page.getByRole('button', {name: 'Add Fixed camera to cart', exact: true}).click();
    await page.waitForFunction(() => document.querySelector('[data-cart-count]').textContent === '1');
    await page.getByRole('button', {name: 'View Starting package', exact: true}).click();
    await page.locator('#detail-add-cart').click();
    await page.waitForFunction(() => document.querySelector('[data-cart-count]').textContent === '2');
    await page.getByRole('button', {name: 'Close product details', exact: true}).click();
    await page.getByRole('button', {name: 'Add Quote WiFi to cart', exact: true}).click();
    await page.waitForFunction(() => document.querySelector('[data-cart-count]').textContent === '3');
    await open(); await page.locator('.cart-item').nth(2).waitFor();
    assert.equal(await total(), 'RM 30.25');
    assert.equal(await page.locator('#cart-total-label').textContent(), 'Estimated total');
    assert.match(await page.locator('.cart-price-note').textContent(), /Quote-only items are excluded/);
    await page.getByRole('button', {name: 'Increase quantity of Fixed camera', exact: true}).click();
    assert.equal(await total(), 'RM 40.50');
    const quantity = page.getByRole('spinbutton', {name: 'Quantity of Fixed camera', exact: true});
    await quantity.fill('3'); await quantity.press('Tab');
    assert.equal(await total(), 'RM 50.75');
    await quantity.fill('0'); await quantity.press('Tab');
    assert.equal(await quantity.inputValue(), '3');
    await page.getByRole('button', {name: 'Remove Starting package', exact: true}).click();
    assert.equal(await total(), 'RM 30.75');
    assert.equal(await page.locator('.cart-item').count(), 2);
    await page.getByRole('button', {name: 'Close cart', exact: true}).click();
    repriced = true;
    await page.goto('http://localhost:8080/index.html');
    await page.waitForFunction(() => document.querySelector('[data-cart-count]').textContent === '4');
    assert.equal(await page.locator('[data-cart-count]').textContent(), '4');
    await open(); await page.locator('.cart-item').nth(1).waitFor();
    assert.equal(await total(), 'RM 37.05');
    await page.screenshot({path: '.preview/cart-desktop.png'});
    await page.getByRole('button', {name: 'Close cart', exact: true}).click();
    await page.setViewportSize({width: 390, height: 844});
    await page.goto('http://localhost:8080/catalogue.html?category=WiFi%20Solutions');
    await page.locator('.product-card').waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await open(); await page.locator('.cart-item').nth(1).waitFor();
    assert.equal(await page.locator('.cart-dialog').evaluate(e => e.scrollWidth <= e.clientWidth), true);
    await page.screenshot({path: '.preview/cart-mobile.png'});
    await page.getByRole('button', {name: 'Close cart', exact: true}).click();
    unpublished = true; await page.reload(); await open();
    await page.getByText('No longer available — remove this item', {exact: true}).waitFor();
    assert.equal(await total(), 'RM 0.00');
    assert.equal(await page.getByRole('spinbutton', {name: 'Quantity of same-id', exact: true}).isDisabled(), true);
    await page.getByRole('button', {name: 'Clear cart', exact: true}).click();
    await page.getByText('Your cart is empty', {exact: true}).waitFor();
    await page.getByRole('button', {name: 'Close cart', exact: true}).click();
    await page.reload(); assert.equal(await page.locator('[data-cart-count]').textContent(), '0');
    assert.deepEqual(errors, []);
    console.log('Cart add, detail add, quantities, validation, removal, mixed pricing, persistence, repricing, unavailable products, clear and mobile checks passed.');
  } finally {await browser.close();}
})().catch(error => {console.error(error); process.exitCode = 1;});
