const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const products=[{id:'camera',name:'Camera',category:'CCTV Systems',description:'CAM-01',image:'assets/products/cctv.svg',price:100,price_mode:'fixed',published:true},{id:'card',name:'64GB Card',category:'PWP Products',description:'SD64',image:'assets/products/microsd-64gb.svg',price:35,price_mode:'fixed',published:true},{id:'quote',name:'Quote system',category:'CCTV Systems',price:0,price_mode:'quote',published:true}];let promotions=[],writes=0;
 const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS'};
 await page.route('https://ab-tech-catalogue-auth.johern20154.workers.dev/staff/**',async r=>{const req=r.request(),path=new URL(req.url()).pathname;if(req.method()==='OPTIONS')return r.fulfill({status:204,headers});let json={configured:true,loginConfigured:true};if(path.endsWith('/login'))json={token:'b'.repeat(64),username:'staff'};if(path.endsWith('/categories'))json={categories:[{name:'CCTV Systems',slug:'cctv',description:'Cameras',icon:'cctv'}],sha:'a'.repeat(40)};if(path.endsWith('/promotions')){if(req.method()==='PUT'){promotions=req.postDataJSON().promotions;writes++;}json={promotions,products,sha:'c'.repeat(40),message:'Saved promotion settings.'};}return r.fulfill({headers,json});});
 await page.goto('http://localhost:8080/admin/');await page.locator('#login-username').fill('staff');await page.locator('#login-password').fill('Camera1!');await page.locator('#staff-login').click();await page.locator('#staff-workspace').waitFor();assert.equal(await page.locator('#staff-category-title').isVisible(),false);
 await page.locator('#staff-promotions-open').click();await page.getByRole('button',{name:'Add promotion +',exact:true}).click();await page.locator('[data-promotion-form] [name="name"]').fill('October camera sale');await page.locator('[name="start"]').fill('2026-10-04');await page.locator('[name="end"]').fill('2026-10-31');await page.locator('[data-add-products]').click();
 assert.equal(await page.locator('.promotion-picker-row').count(),2);await page.locator('[data-category]').selectOption('CCTV Systems');assert.equal(await page.locator('.promotion-picker-row').count(),1);await page.locator('.promotion-picker-row input').check();await page.locator('[data-category]').selectOption('');await page.locator('[data-search]').fill('SD64');assert.equal(await page.locator('.promotion-picker-row').count(),1);await page.locator('.promotion-picker-row input').check();await page.locator('[data-search]').fill('');assert.equal(await page.locator('[data-selection-count]').textContent(),'2 selected');await page.screenshot({path:'.preview/promotions-product-picker.png',fullPage:true});await page.locator('[data-picker-confirm]').click();
 const rows=page.locator('.promotion-product-row');await rows.nth(0).locator('input[type="number"]').first().fill('80');await rows.nth(0).getByText('No limit',{exact:true}).click();await rows.nth(0).locator('input[type="number"]').nth(1).fill('100');await rows.nth(1).locator('select').selectOption('percent');await rows.nth(1).locator('input[type="number"]').first().fill('10');await page.locator('[data-save-promotion]').click();await page.locator('[data-promotion-form]').waitFor({state:'hidden'});assert.equal(writes,1);assert.deepEqual(promotions[0].products,[{key:'CCTV Systems:camera',mode:'price',value:80,limit:100},{key:'PWP Products:card',mode:'percent',value:10,limit:null}]);
 await page.getByRole('button',{name:'Edit promotion',exact:true}).click();assert.equal(await rows.nth(0).locator('input[type="number"]').first().inputValue(),'80');await page.screenshot({path:'.preview/promotions-admin-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'.preview/promotions-admin-mobile.png',fullPage:true});await page.locator('[data-add-products]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('[data-picker-cancel]').click();await page.locator('[data-cancel-promotion]').click();await page.locator('#staff-category-menu summary').click();assert.equal(await page.locator('.promotions-admin').isVisible(),true);assert.deepEqual(errors,[]);console.log('Promotion multi-product selection, search, category filter, discounts, total limits, saving/editing and mobile layout passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
