import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {onRequest} from '../functions/_middleware.js';
import {renderCatalogue,productMarkup} from '../catalogue-render.mjs';
const template=await readFile(new URL('../catalogue.html',import.meta.url),'utf8');
export function context(query='',overrides={}) {return {request:new Request('https://example.com/catalogue'+query),next:async()=>new Response(template,{headers:{'content-type':'text/html'}}),env:{ASSETS:{fetch:async url=>{const path=new URL(url).pathname;return new Response(JSON.stringify(path in overrides?overrides[path]:JSON.parse(await readFile(new URL('..'+path,import.meta.url),'utf8'))));}}}};}
test('category response contains complete visible products, prices and hydration data',async()=>{const response=await onRequest(context('?category=CCTV%20Systems'));const html=await response.text();assert.equal(response.headers.get('X-Catalogue-Rendered'),'server');assert.match(html,/<h1 id="catalogue-page-title">CCTV Systems<\/h1>/);assert.match(html,/class="product-card"/);assert.match(html,/aria-busy="false"/);assert.match(html,/<div id="category-landing" hidden>/);assert.doesNotMatch(html,/<strong id="total-count">10</);});
test('new category works automatically; hidden categories and unpublished products excluded',async()=>{const data={'/data/categories.json':{categories:[{name:'New category',slug:'new-category',description:'New'},{name:'Hidden',slug:'hidden',visible:false}]},'/data/categories/new-category.json':{products:[{id:'one',name:'Visible',published:true,price:20,price_mode:'fixed'},{id:'two',name:'Secret unpublished',published:false}]}};const html=await(await onRequest(context('?category=New%20category',data))).text();assert.match(html,/>Visible</);assert.doesNotMatch(html,/Secret unpublished/);const hidden=await onRequest(context('?category=Hidden',data));assert.equal(hidden.headers.get('X-Catalogue-Rendered'),null);});
test('unsafe product text and script payload are escaped',()=>{const p={name:'</script><script>alert(1)</script>',category:'Test',image:'javascript:alert(1)',price:10,price_mode:'fixed'};const html=renderCatalogue(template,{products:[p],categories:[],promotions:[],offers:[]},null);assert.doesNotMatch(html,/<script>alert/);assert.match(html,/assets\/products\/cctv.svg/);assert.match(html,/\\u003c\/script>/);});
test('discount periods use current time and PWP/New Arrival badges coexist',()=>{const p={id:'a',category:'Test',name:'Test',price:100,price_mode:'fixed',new_arrival:true};const promotions=[{enabled:true,start:'2026-10-01',end:'2026-10-04',products:[{key:'Test:a',limit:null,mode:'percent',value:20}]}];const offers=[{enabled:true,qualifiers:['Test:a']}];assert.match(productMarkup(p,0,promotions,offers,new Date('2026-10-03')),/20% OFF/);const expired=productMarkup(p,0,promotions,offers,new Date('2026-10-05'));assert.doesNotMatch(expired,/20% OFF/);assert.match(expired,/NEW ARRIVAL/);assert.match(expired,/>PWP</);});
