import {productKey} from '../pwp.js';
export function setupPromotionsAdmin(api,isBusy,setBusy) {
  const content=document.querySelector('.staff-content'), sidebar=document.querySelector('.staff-category-sidebar');
  const open=document.createElement('button');open.type='button';open.className='button secondary';open.id='staff-promotions-open';open.textContent='Discount promotions';sidebar.append(open);
  const pane=document.createElement('section');pane.className='promotions-admin';pane.hidden=true;
  pane.innerHTML=`<div class="staff-content-heading"><div><span class="eyebrow">Staff workspace</span><h2>Discount promotions</h2></div><button type="button" class="button" data-new-promotion>Add promotion +</button></div><p class="account-message" role="status" data-promotion-status></p><div data-promotions></div><form data-promotion-form hidden><h3 data-form-heading>Add discount promotion</h3><div class="product-fields"><label class="full-field">Discount Promotion Name<input name="name" required maxlength="100"></label><label>Start date<input name="start" type="date" required></label><label>End date<input name="end" type="date" required></label></div><p class="field-help">Promotion period uses Malaysia time. Both start and end dates are included.</p><div class="promotion-products-heading"><h4>Promotion products</h4><button type="button" class="button secondary" data-add-products>Add product +</button></div><p class="field-help">Select products with fixed prices. Set a special price or a percentage discount for each product.</p><div data-selected-products></div><p class="promotion-limit-note">Purchase limits mean total discounted units sold across all customers. No limit removes this cap. No-limit promotions apply to the shop and cart during their dates. Capped promotions remain inactive until completed-payment sales counting is connected.</p><label class="checkbox-field"><input name="enabled" type="checkbox" checked>Promotion enabled</label><p class="account-message" role="status" data-form-message></p><div class="product-form-actions"><button class="button" data-save-promotion>Save &amp; publish</button><button type="button" class="button secondary" data-cancel-promotion>Cancel</button></div></form>`;
  content.append(pane);
  const picker=document.createElement('dialog');picker.className='promotion-picker staff-product-dialog';picker.innerHTML=`<div class="staff-content-heading"><h2>Select products</h2><button type="button" class="promotion-picker-close" aria-label="Close product selection">×</button></div><div class="promotion-filters"><label>Category<select data-category><option value="">All categories</option></select></label><label>Search product<input type="search" placeholder="Product name or model number" data-search></label></div><p class="field-help">Showing visible products with fixed prices. Products without a fixed price cannot be discounted.</p><label class="checkbox-field"><input type="checkbox" data-select-all>Select all shown products</label><div class="promotion-picker-list" data-picker-list></div><div class="product-form-actions"><span data-selection-count></span><button type="button" class="button secondary" data-picker-cancel>Cancel</button><button type="button" class="button" data-picker-confirm>Confirm</button></div>`;document.body.append(picker);
  const $=s=>pane.querySelector(s), $$=s=>picker.querySelector(s), form=$('[data-promotion-form]');
  let promotions=[], products=[],sha,editing=-1,rows=[],selection=new Set();
  const money=v=>new Intl.NumberFormat('en-MY',{style:'currency',currency:'MYR'}).format(v);
  const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
  const notice=(selector,text,error=false)=>{const node=$(selector);node.textContent=text;node.dataset.error=String(error);};
  function hide(){pane.hidden=true;open.setAttribute('aria-pressed','false');}
  sidebar.addEventListener('click',event=>{if(event.target.closest('#staff-pwp-open,#staff-categories button'))hide();},true);
  function list(){const list=$('[data-promotions]');list.replaceChildren();if(!promotions.length)list.append(el('p','No discount promotions yet.','field-help'));promotions.forEach((promotion,index)=>{
    const card=el('article',undefined,'pwp-offer-card'),copy=el('div'),actions=el('div',undefined,'staff-product-actions');copy.append(el('h3',promotion.name),el('p',`${promotion.start} → ${promotion.end} · ${promotion.products.length} products · ${promotion.enabled?'Enabled':'Paused'}`,'field-help'));
    const edit=el('button','Edit promotion'),remove=el('button','Delete');edit.type=remove.type='button';edit.onclick=()=>editPromotion(index);remove.onclick=async()=>{if(isBusy()||!confirm('Delete '+promotion.name+'?'))return;setBusy(true);try{await publish(promotions.filter((_,i)=>i!==index));form.hidden=true;}catch(e){notice('[data-promotion-status]',e.message,true);}finally{setBusy(false);}};actions.append(edit,remove);card.append(copy,actions);list.append(card);
  });}
  async function publish(next){const data=await api('promotions',{method:'PUT',body:JSON.stringify({sha,promotions:next})});sha=data.sha;promotions=data.promotions;list();notice('[data-promotion-status]',data.message);}
  function selectedRows(){const container=$('[data-selected-products]');container.replaceChildren();rows.forEach(row=>{
    const product=products.find(p=>productKey(p)===row.key),card=el('article',undefined,'promotion-product-row');card.append(el('h4',product?.name||'Unavailable product'),el('p',product?`${product.category} · Normal price ${money(product.price)}`:'Remove this unavailable product.','field-help'));
    const fields=el('div',undefined,'product-fields'),modeLabel=el('label','Discount type'),mode=el('select');for(const [value,text] of [['price','Discounted price (RM)'],['percent','Percentage (%)']]){const option=el('option',text);option.value=value;mode.append(option);}mode.value=row.mode;modeLabel.append(mode);
    const valueLabel=el('label',row.mode==='price'?'Discounted price (RM)':'Discount (%)'),value=el('input');value.type='number';value.min='.01';value.step='.01';value.required=true;value.value=row.value??'';value.max=row.mode==='percent'?'99.99':product?((Math.round(product.price*100)-1)/100).toFixed(2):'';valueLabel.append(value);
    const preview=el('p','','field-help');function update(){row.value=value.value===''?null:Number(value.value);const price=row.mode==='price'?row.value:product?.price*(1-row.value/100);preview.textContent=row.value&&product?`Discounted price: ${money(price)}`:'';}value.oninput=update;mode.onchange=()=>{row.mode=mode.value;row.value=null;selectedRows();};update();
    const limitLabel=el('label','Total promotional sales limit'),limit=el('input');limit.type='number';limit.min='1';limit.max='1000000';limit.step='1';limit.required=true;limit.disabled=row.limit===null;limit.value=row.limit??'';limit.oninput=()=>row.limit=Number(limit.value);limitLabel.append(limit);
    const unlimitedLabel=el('label',undefined,'checkbox-field'),unlimited=el('input');unlimited.type='checkbox';unlimited.checked=row.limit===null;unlimited.onchange=()=>{row.limit=unlimited.checked?null:1;selectedRows();};unlimitedLabel.append(unlimited,el('span','No limit'));
    fields.append(modeLabel,valueLabel,limitLabel,unlimitedLabel);const remove=el('button','Remove product','promotion-remove');remove.type='button';remove.onclick=()=>{rows=rows.filter(r=>r!==row);selectedRows();};card.append(fields,preview,remove);container.append(card);
  });}
  function editPromotion(index){if(isBusy()||!sha)return;editing=index;form.reset();const promotion=promotions[index];for(const key of ['name','start','end'])form.elements[key].value=promotion?.[key]||'';form.elements.end.min=form.elements.start.value;form.elements.enabled.checked=promotion?.enabled??true;rows=(promotion?.products||[]).map(r=>({...r}));$('[data-form-heading]').textContent=promotion?'Edit discount promotion':'Add discount promotion';notice('[data-form-message]','');selectedRows();form.hidden=false;form.elements.name.focus();}
  function filtered(){const query=$$('[data-search]').value.trim().toLowerCase(),category=$$('[data-category]').value;return products.filter(p=>p.price_mode==='fixed'&&p.price>.01&&(!category||p.category===category)&&`${p.name} ${p.description||''}`.toLowerCase().includes(query));}
  function selectionCount(){const visible=filtered();$$('[data-selection-count]').textContent=`${selection.size} selected`;$$('[data-picker-confirm]').disabled=selection.size===0;$$('[data-select-all]').checked=visible.length>0&&visible.every(p=>selection.has(productKey(p)));$$('[data-select-all]').indeterminate=visible.some(p=>selection.has(productKey(p)))&&!$$('[data-select-all]').checked;}
  function pickerList(){const container=$$('[data-picker-list]');container.replaceChildren();for(const product of filtered()){
    const label=el('label',undefined,'promotion-picker-row'),check=el('input');check.type='checkbox';check.value=productKey(product);check.checked=selection.has(check.value);check.onchange=()=>{check.checked?selection.add(check.value):selection.delete(check.value);selectionCount();};const image=el('img');const path=/^assets\/(products|uploads)\/[a-zA-Z0-9_. -]+$/.test(product.image||'')?product.image:'assets/products/cctv.svg';image.src=new URL('../'+path,import.meta.url).href;image.alt='';const copy=el('span');copy.append(el('strong',product.name),el('small',product.category+' · '+(product.description||product.id)));label.append(check,image,copy,el('span',money(product.price)));container.append(label);
  }if(!container.children.length)container.append(el('p','No matching eligible products.','field-help'));selectionCount();}
  $('[data-add-products]').onclick=()=>{selection=new Set(rows.map(r=>r.key));$$('[data-search]').value='';const category=$$('[data-category]');category.replaceChildren(new Option('All categories',''),...[...new Set(products.map(p=>p.category))].map(c=>new Option(c,c)));pickerList();picker.showModal();};
  $$('[data-search]').oninput=pickerList;$$('[data-category]').onchange=pickerList;$$('[data-select-all]').onchange=event=>{for(const product of filtered())event.target.checked?selection.add(productKey(product)):selection.delete(productKey(product));pickerList();};
  for(const selector of ['.promotion-picker-close','[data-picker-cancel]'])$$(selector).onclick=()=>picker.close();
  $$('[data-picker-confirm]').onclick=()=>{rows=[...selection].map(key=>rows.find(r=>r.key===key)||{key,mode:'price',value:null,limit:null});selectedRows();picker.close();};
  $('[data-new-promotion]').onclick=()=>editPromotion(-1);$('[data-cancel-promotion]').onclick=()=>{if(!isBusy())form.hidden=true;};
  form.elements.start.onchange=()=>{form.elements.end.min=form.elements.start.value;};
  form.onsubmit=async event=>{event.preventDefault();if(isBusy())return;if(!rows.length){notice('[data-form-message]','Add at least one product.',true);return;}if(form.elements.start.value>form.elements.end.value){notice('[data-form-message]','End date must be on or after the start date.',true);return;}
    const promotion={id:promotions[editing]?.id||'promotion-'+crypto.randomUUID(),name:form.elements.name.value.trim(),start:form.elements.start.value,end:form.elements.end.value,enabled:form.elements.enabled.checked,products:rows};const next=promotions.slice();if(editing<0)next.push(promotion);else next[editing]=promotion;setBusy(true);$('[data-save-promotion]').disabled=true;try{await publish(next);form.hidden=true;}catch(e){notice('[data-form-message]',e.message,true);}finally{setBusy(false);$('[data-save-promotion]').disabled=false;}
  };
  open.onclick=async()=>{if(isBusy())return;for(const child of content.children)child.hidden=true;pane.hidden=false;form.hidden=true;open.setAttribute('aria-pressed','true');document.getElementById('staff-pwp-open').setAttribute('aria-pressed','false');document.querySelectorAll('#staff-categories button').forEach(b=>b.setAttribute('aria-pressed','false'));setBusy(true);$('[data-new-promotion]').disabled=true;notice('[data-promotion-status]','Loading promotions and products…');try{const data=await api('promotions');promotions=data.promotions;products=data.products;sha=data.sha;list();notice('[data-promotion-status]','');}catch(e){sha=null;notice('[data-promotion-status]',e.message,true);}finally{setBusy(false);$('[data-new-promotion]').disabled=!sha;}};
  return {reset(){hide();picker.close();form.hidden=true;promotions=[];rows=[];sha=null;}};
}
